### ISSUE TITLE
SafeAdd klab build failed

### ISSUE THREAD

**Issue by chenIshi** [dapphub/klab#211]
After following the instruction of installing klab, I tried to test it on SafeAdd and it failed.

```
undefined:1



SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at toJson (/home/chenishi/git-repos/klab/lib/config.js:15:28)
    at Object.keys.forEach.alias (/home/chenishi/git-repos/klab/lib/config.js:88:17)
    at Array.forEach (<anonymous>)
    at module.exports (/home/chenishi/git-repos/klab/lib/config.js:83:6)
    at Object.<anonymous> (/home/chenishi/git-repos/klab/lib/storage.js:16:23)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
```

However, I apply `klab build` on both `d0_suck` and `token`, they both function well.

```
Token_transfer_pass_rough
Token_transfer_fail
write prelude
write rules.k
```

**Comment by livnev** [comment]
@chenIshi Hi, thanks for reporting this. I'm unable to reproduce this with the latest `master.` Could you check that the repo is checked out properly and that you are on the latest `master`?

**Comment by chenIshi** [comment]
![image](https://user-images.githubusercontent.com/22028523/59274636-51132f80-8c8d-11e9-8f10-9df140113b71.png)

It was in branch `v0.2.4`, which seems to be a little bit out-dated (but stable maybe?), I just did it on this branch according to what readme.md said.

**Comment by chenIshi** [comment]
And also branch `v2.0.4` didn't have the file `env` to config environment variable
Maybe should update readme.md to a newer version ?

**Comment by livnev** [comment]
@chenIshi Good call, we needed to update the `v0.2.4` tag. I've just pushed `v0.2.4` to the latest `master`. Please let us know if you have any other issues.
