### ISSUE TITLE
ReferenceError: moment is not defined

### ISSUE THREAD

**Issue by livnev** [dapphub/klab#25]
Ran into this strange error, with `klab server` crashing unexpectedly:

```18.07.24 00-53-33: exec /home/lev/src/k/latest/evm-semantics/.build/k/k-distribution/target/release/k/bin/kprove --debugg --debugg-path /tmp/klab/b87ea886502a47666d3a993205cb6a40a04f3c1b7de47d433ddd3aa928089277 --directory /home/lev/src/k/latest/evm-semantics/.build/java/ --z3-executable ./proof-spec.k --def-module VERIFICATION --output-tokenize #And _==K_ <k> #unsigned --output-omit <programBytes> <program> <code> --output-flatten _Map_ #And --output json --smt_prelude ./prelude.smt2 --z3-tactic "(or-else (using-params smt :random-seed 3 :timeout 1000) (using-params smt :random-seed 2 :timeout 2000) (using-params smt :random-seed 1))"
18.07.24 00-54-03: out Debugg: /tmp/klab/b87ea886502a47666d3a993205cb6a40a04f3c1b7de47d433ddd3aa928089277

18.07.24 00-54-23: error missing SMTLib translation for _&Int__INT
 b87ea886502a47666d3a993205cb6a40a04f3c1b7de47d433ddd3aa928089277
18.07.24 00-54-24: error missing SMTLib translation for _&Int__INT
 b87ea886502a47666d3a993205cb6a40a04f3c1b7de47d433ddd3aa928089277
18.07.24 00-54-24: error missing SMTLib translation for _&Int__INT
 b87ea886502a47666d3a993205cb6a40a04f3c1b7de47d433ddd3aa928089277
18.07.24 00-54-24: error missing SMTLib translation for _&Int__INT
 b87ea886502a47666d3a993205cb6a40a04f3c1b7de47d433ddd3aa928089277
18.07.24 00-54-24: error missing SMTLib translation for _&Int__INT
 b87ea886502a47666d3a993205cb6a40a04f3c1b7de47d433ddd3aa928089277
18.07.24 00-54-24: error missing SMTLib translation for _&Int__INT
 b87ea886502a47666d3a993205cb6a40a04f3c1b7de47d433ddd3aa928089277
/home/lev/src/k/latest/klab/lib/driver/dbDriver.js:21
  let now = moment().format("YY.MM.DD HH-mm-ss")
            ^

ReferenceError: moment is not defined
    at log (/home/lev/src/k/latest/klab/lib/driver/dbDriver.js:21:13)
    at getBlob (/home/lev/src/k/latest/klab/lib/driver/dbDriver.js:33:5)
    at Object.getblob (/home/lev/src/k/latest/klab/lib/driver/dbDriver.js:39:14)
    at Object.next (/home/lev/src/k/latest/klab/lib/driver/dbDriver.js:112:56)
    at Stream._n (/home/lev/src/k/latest/klab/node_modules/xstream/index.js:797:18)
    at /home/lev/src/k/latest/klab/node_modules/@cycle/run/lib/cjs/index.js:57:61
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)```

**Comment by MrChico** [comment]
Added `require('momen');' in dbDriver. Try again and see if this remains?

**Comment by livnev** [comment]
@MrChico Unfortunately I'm not going to be able to reproduce this bug since my environment has changed since then and I didn't even know how to reproduce it at the time :frowning_face: Thanks for looking into it!

**Comment by livnev** [comment]
@MrChico I finally managed to reproduce this again, and checked that your commit does fix the problem. Thanks!
