### ISSUE TITLE
Cannot read property 'NaN' of undefined

### ISSUE THREAD

**Issue by danr** [dapphub/klab#3]
```TypeError: Cannot read property 'NaN' of undefined
    at prev (/home/dan/code/klab/lib/stateHandler.js:139:20)
    at /home/dan/code/klab/node_modules/cycle-onionify/lib/onionify.js:11:54
    at Fold.f (/home/dan/code/klab/node_modules/xstream/index.js:544:40)
    at _try (/home/dan/code/klab/node_modules/xstream/index.js:31:18)
    at Fold._n (/home/dan/code/klab/node_modules/xstream/index.js:562:17)
    at Stream._n (/home/dan/code/klab/node_modules/xstream/index.js:797:18)
    at ConcatProducer._n (/home/dan/code/klab/node_modules/xstream/extra/concat.js:27:11)
    at Stream._n (/home/dan/code/klab/node_modules/xstream/index.js:797:18)
    at Merge._n (/home/dan/code/klab/node_modules/xstream/index.js:125:11)
    at Stream._n (/home/dan/code/klab/node_modules/xstream/index.js:797:18)```g

**Comment by danr** [comment]
This was probably it! It took me some time before I realized steps were rolling in asynchronously.
