### ISSUE TITLE
errors when running klab server, issues with node.js

### ISSUE THREAD

**Issue by denis-bogdanas** [dapphub/klab#51]
I cannot run klab server. 3 attempts to setup node below, all throw different errors.
My setup: didn't run `make deps`, just `make link`.

1. I initially installed just npm, through `sudo apt-get npm; npm install`
For `klab server`
I got:
`/usr/bin/env: ‘node’: No such file or directory`

2. Additionally installed `node` through: `sudo apt-get nodejs-legacy`. Result:

```
$ node --version
v4.2.6
$ klab server
/mnt/d/klab/libexec/klab-server:4
const {run} = require("@cycle/run");
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
```

3. Uninstalled npm and nodejs-legacy, installed node v6 instead:

```
$ sudo curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
## Installing the NodeSource Node.js 6.x LTS Boron repo...

$ sudo apt-get install -y nodejs
$ node --version
v6.14.4
$ klab server
/mnt/d/klab/libexec/klab-server:39
      ...state,
      ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:160:9)
```

What version of `node` do you have?

**Comment by MrChico** [comment]
I have node version `v9.8.0` for which everything works fine

**Comment by denis-bogdanas** [comment]
Then the installation instructions are misleading. Readme says that NPM is required. I installed it as you would expect one to do on Ubuntu, and got the wrong version.

I Installed nodejs v9.11.2 after all. But now I get this error:
```
$ klab server
internal/modules/cjs/loader.js:550
    throw err;
    ^

Error: Cannot find module 'xstream'
```

Are you sure there are no other dependencies?

**Comment by denis-bogdanas** [comment]
Thanks. It works now.
